version: "3.8"
services:
    publisher:
        build: ./publisher
        container_name: publisher_log
        tty: true
        ports:
            - 5000:5000
        volumes:
            - ./publisher/app:/app
        env_file:
            - ./publisher/.env
        networks:
            - rabbit_net
            - proxy

    consumer:
        build: ./consumer
        container_name: consumer_log
        tty: true
        restart: always
        ports:
            - 5005:5005
        volumes:
            - ./consumer/app:/app
        env_file:
            - ./consumer/.env
        networks:
            - rabbit_net
            - db_net

    # nginx:
    #     image: nginx:latest
    #     volumes:
    #         - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
    #     ports:
    #         - 5015:5000
    #     expose:
    #         - 5015
    #     env_file:
    #         - ./nginx/.env
    #     depends_on:
    #         - publisher
    #         - proxy

networks:
    rabbit_net:
        external: true
    db_net:
        external: true
    proxy:
        external: true
